/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle;

import com.google.gson.Gson;

public class App {
    public static void main( String[] args ){
        Student usenko = new Student("Artem", "Usenko");
        System.out.println(new Gson().toJson(usenko));
    }
}
