/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle;

import com.google.gson.Gson;

import java.util.Collections;
import java.util.Map;

public class App {
    public static void main(String[] args) {
        Map<String, String> human = Collections.singletonMap("name", "John Doe");
        System.out.println("new Gson().toJson(human) = " + new Gson().toJson(human));
    }
}
